title: Site Snapshot
description: This Add-On will create a PDF snapshot of a site and upload the document to your DocumentCloud account. 
type: object
documents: []
properties:
  type: array
  sites:
    items:
      title: URL
      type: string
      format: uri
required: [sites]
