title: Site Snapshot
description: This Add-On will create a PDF snapshot of a site and upload the document to your DocumentCloud account. 
type: object
documents: []
properties:
  project_id:
    title: Project ID
    type: integer
  access_level:
    title: Access level (public, private, organization)
    type: string
    default: private
  sites:
    type: array
    default: [""]
    items:
      title: URL
      type: string
      format: uri
required: [sites]
categories:
  - monitor
