title: Site Snapshot
description: This Add-On will create a PDF snapshot of a site and upload the document to your DocumentCloud account. 
type: object
documents: []
properties:
  project_id:
    title: If you would like to add these snapshots to a DocumentCloud project, provide the ID here. 
    type: integer
  sites:
    type: array
    default: [""]
    items:
      title: URL
      type: string
      format: uri
required: [sites]
