title: Hello World
description: This is an updated simple test add-on
type: object
documents: []
properties:
  site:
    type: array
    default: [""]
    items:
      title: URL
      type: string
      format: uri
required: [site]
